---
title: 'Variant comparison report'
author: 'University of Melbourne Centre for Cancer Research'
date: '`r Sys.time()`'
output:
  html_document:
    theme: cosmo
code_download: true
params:
  results_directory: '~/projects/woof_nf/output/'
---

```{r knitr_options, include=FALSE}
knitr::opts_chunk$set(
  collapse=TRUE,
  echo=FALSE,
  warning=FALSE,
  message=FALSE
)
```

```{css}
.main-container {
  max-width: 1400px;
}

#header {
  margin-top: 10px;
}

.main-container h1 {
  margin-top: -10px;
}

details {
  padding-bottom: 20px;
}

.details-container {
  margin-top: 25px;
  margin-left: 50px;
}
```

```{r libraries}
library(bedr)
library(DT)
library(tidyverse)
```

```{r global_formatting}
v.table_cell_fill_colour_green <- '#bce3ca'
v.table_cell_fill_colour_yellow <- '#f2cc8f'
v.table_cell_fill_colour_red <- '#ffcbc6'
v.table_cell_fill_range <- c(0.97, 1)

v.table_filter_options <- list(position='top', clear=FALSE, plain=FALSE)

v.table_display_max <- 500
```

```{r shared_functions}
# Subset to n variants across samples
subset_variants <- function(d.variants, n.total=15) {
  # Get variant display count for each sample
  v.variant_display_count <- get_variant_display_counts(d.variants %>% dplyr::count(`Sample name`), n.total)
  # Some sanity checks
  v.sample_names <- unique(d.smlv_pcgr_data$`Sample name`)
  all(v.sample_names %in% names(v.variant_display_count))
  length(v.sample_names) == length(v.variant_display_count)
  # Subet and bind results
  unique(d.variants$`Sample name`) %>%
    purrr::map(function(s.name) {
      n.variants <- v.variant_display_count[s.name]
      if (n.variants < 1) {
        return(d.variants[NULL, ])
      }
      d.variants %>%
        dplyr::filter(`Sample name`==s.name) %>%
        dplyr::slice(1:n.variants)
    }) %>%
    dplyr::bind_rows()
}

# Get variant counts for subsetting
get_variant_display_counts <- function(d.variant_counts, n.total) {
  # Set initial target per sample
  n.total_sample <- n.total / nrow(d.variant_counts)
  # Iterate variant counts from lowest to highest
  d.variant_counts <- dplyr::arrange(d.variant_counts, n)
  v.variants_sorted <- setNames(d.variant_counts$n, d.variant_counts$`Sample name`)
  v.sample_take <- setNames(rep(0, length(v.variants_sorted)), names(v.variants_sorted))
  for (i in 1:length(v.variants_sorted)) {
    # Determine number of variants to take (after rounding) and difference between target
    n.take <- round(min(v.variants_sorted[i], n.total_sample), 0)
    n.remaining <- n.total_sample - n.take
    # If current sample has less variants than target, distribute difference across remaining samples
    if (n.remaining) {
      n.sample_extra <- n.remaining / (length(v.variants_sorted) - i)
      n.total_sample <- n.total_sample + n.sample_extra
    }
    v.sample_take[i] <- n.take
  }
  return(v.sample_take)
}

# Warnings - missing file expandable
render_warning_files <- function(d.missing_files) {
  s.summary_text_templ <- '
  <summary>
    <span style="color: #e9c46a;">Missing <b>${length(v.files_missing)}</b> expected ${s.plurality}</span>
    <span style="color: #b0b0b0;">(click for details)</span>
  </summary>
  '
  v.files_missing <- d.missing_files$file
  s.plurality <- ifelse(length(v.files_missing) > 1, 'files', 'file')
  s.summary_text <- stringr::str_interp(s.summary_text_templ)

  cat('<details>', s.summary_text, '<div class="details-container">', sep='')
  cat(
    d.missing_files %>%
      knitr::kable(format='html') %>%
      kableExtra::kable_styling(full_width=FALSE, position='left')
  )
  cat('</div></details>', sep='')
}

# Warnings - missing variants expandable
# NOTE: currently only used once by the small variant PCGR variant table. If this remains true, remove as generalised fn
render_warning_variants <- function(d.display_data) {
  s.summary_text_templ <- '
  <summary>
    <span style="color: #e9c46a;">Not displaying <b>${n.variants_undisplayed}</b> ${s.plurality}</span>
    <span style="color: #b0b0b0;">(click for details)</span>
  </summary>
  '
  n.variants_undisplayed <- sum(d.display_data$`Not displayed`)
  s.plurality <- ifelse(n.variants_undisplayed > 1, 'variants', 'variant')
  s.summary_text <- stringr::str_interp(s.summary_text_templ)

  cat('<details>', s.summary_text, '<div class="details-container">', sep='')
  cat(
    d.display_data %>%
      knitr::kable(format='html') %>%
      kableExtra::kable_styling(full_width=FALSE, position='left')
  )
  cat('</div></details>', sep='')
}

# Warnings - summarise missing variants
# NOTE: see above re single usage
get_variant_display_data <- function(d.full, d.subset) {
  # Set columns and display names
  v.column_display_names <- c(
    'Sample name',
    'Displayed'='displayed',
    'Not displayed'='not_displayed',
    'Total'='total'
  )
  # For each sample, get count of total variants, displayed variants, and undisplayed variants
  # 1. count total variants
  # 2. count displayed variants
  # 3. bind rows and cast to wider format
  # 4. rename and order columns
  d.counts_full <- d.full %>%
    dplyr::group_by(`Sample name`) %>%
    dplyr::summarise(n=n()) %>%
    dplyr::mutate(type='total')
  d.counts_subset <- d.subset %>%
    dplyr::group_by(`Sample name`) %>%
    dplyr::summarise(n=n()) %>%
    dplyr::mutate(type='displayed')
  dplyr::bind_rows(
    d.counts_full,
    d.counts_subset,
  ) %>%
    tidyr::pivot_wider(names_from=type, values_from=n) %>%
    dplyr::mutate(not_displayed=total-displayed) %>%
    dplyr::select(tidyselect::all_of(v.column_display_names))
}
```

```{r sample_input_directories}
v.sample_dirs <- fs::dir_ls(params$results_directory, glob='/*', type='directory')
```

```{r child='report_overview.Rmd'}
```

```{r child='report_smlv.Rmd'}
```

```{r child='report_sv.Rmd'}
```

```{r child='report_cnv.Rmd'}
```

```{r child='report_build.Rmd'}
```
