# Build information {.tabset .tabset-fade}
## Report configuration
```{r configuration}
n.table_height <- min(38.75 * (1 + length(v.sample_dirs)) + 21, 600)
dplyr::tibble(
  Sample=v.sample_dirs,
) %>%
  knitr::kable(format='html') %>%
  kableExtra::kable_styling(full_width=FALSE, position='left') %>%
  kableExtra::scroll_box(height=paste0(n.table_height, 'px'))
```

## R packages
```{r packages}
v.packages <- c(
  purrr::map(sessionInfo()$basePkgs, packageDescription),
  sessionInfo()$otherPkgs,
  sessionInfo()$loadedOnly
)
d.packages <- purrr::map(v.packages, function(v.package) {
  s.build_date <- str_extract(v.package$Built, '(20|19)[0-9]{2}-[0-9]{2}-[0-9]{2}')
  tibble::tibble(
    Package=v.package$Package,
    Version=v.package$Version,
    `System path`=find.package(v.package$Package),
    `Build date`=s.build_date
  )
}) %>%
  dplyr::bind_rows() %>%
  dplyr::arrange(`Package`)

d.packages %>%
  knitr::kable(format='html') %>%
  kableExtra::kable_styling(full_width=TRUE, position='left') %>%
  kableExtra::column_spec(1, bold=TRUE) %>%
  kableExtra::scroll_box(height='600px')
```