{% set version = "0.1.1" %}

package:
  name: woof-nf
  version: {{ version }}

source:
  path: ../../

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - bcftools ==1.12
    - boto3
    - circos >=0.69.8
    - nextflow ==21.04.0
    - openjdk ==11.0.8
    - python >=3.7
    - r-base >=3.5
    - r-bedr
    - r-dt
    - r-glue
    - r-kableextra
    - r-rock
    - r-tidyverse
    - r-woofr

test:
  imports:
    - woof_nf

about:
  home: https://github.com/scwatts/woof-nf
  license: GPL
