{% set version = "0.2.5" %}

package:
  name: woof-nf
  version: {{ version }}

source:
  path: ../../

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python ==3.9.6
    - pip ==21.2.4
    # Needed to fix macOS installation, see post-link.sh
    - perl-app-cpanminus ==1.7044
  run:
    - bcftools ==1.12
    - boto3 ==1.18.22
    - circos ==0.69.8
    - nextflow ==21.04.0
    - openjdk ==11.0.8
    - python ==3.9.6
    - r-base ==3.6.3
    - r-bedr ==1.0.7
    - r-dt ==0.18
    - r-glue ==1.4.2
    - r-kableextra ==1.3.4
    - r-rock ==0.0.17
    - r-tidyverse ==1.3.1
    # Only required for umccr_cancer_genes.latest.genes
    - r-woofr ==0.1.20

test:
  imports:
    - woof_nf

about:
  home: https://github.com/scwatts/woof-nf
  description: Comparison framework for genomic variants called from the same sample by different methods
  license: GPL
